kind: PersistentVolume
apiVersion: v1
metadata:
  name: namenode-hadoop
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/namenode"
