apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-hdfs-kerberos
  namespace: hdfs-kerberos
spec:
  type: Scala
  mode: cluster
  image: "mesosphere/spark:2.4.4-hadoop-2.9-k8s"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.HdfsTest
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.4.jar"
  sparkConf:
    "spark.kubernetes.driverEnv.HADOOP_TOKEN_FILE_LOCATION": "/var/keytabs/delegation.token"
  arguments:
    - "hdfs://namenode.hdfs-kerberos.svc.cluster.local:9000/spark/README.txt"
  volumes:
    - name: keytab
      persistentVolumeClaim:
        claimName: server-keytab
#    - name: krb-config
#      configMap:
#        name: krb5
  hadoopConfigMap: hadoop-conf
  sparkVersion: 2.4.4
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: 2.4.4
    serviceAccount: spark-instance-spark-service-account
    volumeMounts:
      - name: keytab
        mountPath: /var/keytabs
#      - name: krb-config
#        mountPath: /etc/krb5.conf
#        subPath: krb5.conf
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.4
    volumeMounts:
      - name: keytab
        mountPath: /var/keytabs
    env:
      - name: HADOOP_TOKEN_FILE_LOCATION
        value: "/var/keytabs/delegation.token"
