apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-datanode
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hdfs-datanode
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/hostname: datanode
      labels:
        name: hdfs-datanode
        kerberosService: datanode
    spec:
      containers:
      - command:
        - start-datanode.sh
        name: datanode
        image: registry:5000/hadoop-base:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/keytabs
          name: datanode-keytab
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      restartPolicy: Always
      volumes:
      - name: datanode-keytab
        persistentVolumeClaim:
          claimName: server-keytab
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    kerberosService: datanode
  name: datanode
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 0
  selector:
    kerberosService: datanode